### ISSUE TITLE
Can't import Garmin FR230 files - 'Failed to read or parse HRM file'

### ISSUE THREAD

**Issue by QA-Manager** [ssaring/sportstracker#173]
Running 7.4.1, and I have two FR230 files which won't import. Both were created on the same day, and both were created when I wasn't wearing a heart rate monitor. I have imported hundreds of HRM files without any problem, but nearly always wear a monitor - so I suspect that the problem is due to the lack of heart rate data. I can send you a file if you would like to examine it.

**Comment by ssaring** [comment]
The missing hr could be the reason for the error. Please attach an example file, I need it for analyzing the error.

Bye, Stefan

**Comment by QA-Manager** [comment]
I created one this morning in anticipation of your wanting to see one. I ran for a while, saved the data, then removed my HRM and ran a little more. The first file imports fine, the second one generates the parsing error.
[82I72759.zip](https://github.com/ssaring/sportstracker/files/1734983/82I72759.zip)

**Comment by QA-Manager** [comment]
Sorry, clicked the wrong button.

**Comment by ssaring** [comment]
I've just tested your attached file with the recent development version of SportsTracker, it parses and shows it without problems. I've has a similar problem before which has already been fixed.
You should get the latest version from Git (master branch). I hope you are able to build it, otherwise please contact me.

So I'll close this issue.
