### ISSUE TITLE
Average Speed is calculated incorrectly

### ISSUE THREAD

**Issue by QA-Manager** [ssaring/sportstracker#206]
Running 7.6.0, importing Garmin data. After importing the file I click on the 'Main' tab and see:
   - Distance: 4.01 miles
   - Speed (min/m): 8:49
   - Duration: 00:35:21

As soon as I set the 'Sport Type', the average speed changes to '6.805'. The final displayed speed is MPH, not minutes/mile.

**Comment by ssaring** [comment]
Interesting issue - the average speed is always displayed correctly, but the label does not show the proper unit name.
By default (when adding an exercise or when importing a file) the dialog uses the preferred speed mode, so the label displays e.g. "(min/m)". But when the user selects a sport type, then there can be a different speed mode for the selected sport type (e.g. cycling vs. running).
In this case the average speed label needs to display the unit name of the selected sport type speed mode - this has been forgotten.

This error has been fixed in the master branch, will be available in SportsTracker 7.6.1.

Thanks for the error report.
