### ISSUE TITLE
Unable to package SportsTracker 7.7.1

### ISSUE THREAD

**Issue by QA-Manager** [ssaring/sportstracker#228]
I have cloned and built SportsTracker 7.7.1, but haven't been able to package it. I installed OpenJDK 14 and ran the package script but got an error and no package.

:~/Development/Kotlin/SportsTracker/sportstracker/st-packager$ ./package-linux.sh
WARNING: Using incubator modules: jdk.incubator.jpackage
Running [dpkg, --print-architecture]
amd64
Running [dpkg-deb, --version]
Debian 'dpkg-deb' package archive backend version 1.19.7 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
Running [dpkg-deb, --version]
Debian 'dpkg-deb' package archive backend version 1.19.7 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
Running [dpkg, --version]
Debian 'dpkg' package management program version 1.19.7 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
Running [fakeroot, --version]
fakeroot version 1.24
Running [ldd, --version]
ldd (Ubuntu GLIBC 2.31-0ubuntu9) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
jlink arguments: [--output, /tmp/jdk.incubator.jpackage8425283506694546866/images/SportsTracker/lib/runtime, --module-path, /jmods:/usr/lib/jvm/java-14-openjdk-amd64/jmods, --add-modules, java.sql,java.desktop,java.scripting,java.logging,java.net.http,java.xml,jdk.jsobject,jdk.unsupported,java.base,jdk.crypto.ec,jdk.localedata, --strip-native-commands, --strip-debug, --no-man-pages, --no-header-files]
jdk.incubator.jpackage.internal.PackagerException: jlink failed with: Error: Hash of java.xml (5c0470b7e1f23ec63991ae852f2e6985035182851f78a7899873bd00c2035dd7) differs to expected hash (71dcb63fc998b21006f7905f2dcd12792237cc0bcaf257b849d159a144b1fe75) recorded in java.base

at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.JLinkBundlerHelper.runJLink(JLinkBundlerHelper.java:368)
at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.JLinkBundlerHelper.execute(JLinkBundlerHelper.java:183)
at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.LinuxAppBundler.doAppBundle(LinuxAppBundler.java:119)
at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.LinuxAppBundler.doBundle(LinuxAppBundler.java:106)
at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.LinuxPackageBundler.execute(LinuxPackageBundler.java:118)
at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.Arguments.generateBundle(Arguments.java:641)
at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.Arguments.processArguments(Arguments.java:514)
at jdk.incubator.jpackage/jdk.incubator.jpackage.main.Main.execute(Main.java:97)
at jdk.incubator.jpackage/jdk.incubator.jpackage.main.Main.main(Main.java:51)

Please point me in the right direction to fix this.

**Comment by ssaring** [comment]
Which version of Ubuntu and which version of OpenJDK you're using?
Is OpenJDK installed from the Ubuntu repositories or from an OpenJDK distributor, such das AdoptOpenJDK?
On Debian systems you need to install the package "fakeroot", but that seems to be the case as the output looks like.

**Comment by QA-Manager** [comment]
1) Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04

2) java-14-openjdk-amd64, installed from the Ubuntu repositories

**Comment by ssaring** [comment]
You're using the OpenJDK from Ubuntu repos, sounds interesting. I remember that they had a quite interesting, dissected packaging in the past. That means that some basic packages are not installed by default, they needs to be installed in addition. Maybe this is also the case here.

I would suggest you to uninstall the OpenJDK from the Ubuntu repo and to try install the OpenJDK from the AdoptOpenJDK distributor. The installation is documented here: https://adoptopenjdk.net/installation.html
Maybe the packaging works then...

**Comment by QA-Manager** [comment]
I installed OpenJDK14U-jdk_x64_linux_hotspot_14.0.2_12.tar.gz
$ java -version
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.2+12)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.2+12, mixed mode, sharing)

Running the package script gives 'Module not found' errors for all of the modules in the '--add-modules' line. (I removed them one at a time in order to verify that all of them failed the same way.)
java.sql
java.desktop
java.scripting
java.logging
java.net.http
java.xml
jdk.jsobject
jdk.unsupported
java.base
jdk.crypto.ec
jdk.incubator.jpackage.internal.PackagerException: jlink failed with: Error: Module jdk.localedata not found

It appears that there is something else that I need to install, but I don't know what it is. What would you suggest?

**Comment by ssaring** [comment]
Nice to hear that the packaging with AdoptOpenJDK works now. As said, I assume that some dependency has been missing caused by the Ubuntu package separations.
Thanks for reporting the problem with the missing JAVA_HOME variable, I've added it to the packaging documentation. 

Regarding your new problem: it seems there is always an error when opening the ExerciseViewer component for any HRM file. I assume the same behavior when usung File => Open and selecting some HRM file.
It would be very helpful to see the console output in this case. Could you please execute the installed package from the commandline? I can't tell you for sure whether the log output will be visible in that case, maybe it can't be seen because of the native launcher.

If there is no log ouput, could you please try to execute the build application, not the packaged one? This can be done via 'java -jar sportstracker/target/sportstracker-7.7.1-SNAPSHOT.jar (or a similar filename). Maybe there is a general problem in your case.

**Comment by QA-Manager** [comment]
Very interesting...

After building it I installed it with:
$sudo apt install ./sportstracker_7.7.1-SNAPSHOT-1_amd64.deb

and then ran it from the launcher (sidebar) icon. It still said it was version 7.7.0 (I checked 'Help' 'About'), but I didn't think that was a problem.

Today the launcher icon 
is no longer present; running the application from the command line tells me that it is version 7.7.1, and the files import correctly.

The only interesting warning that I saw in the logs was when I clicked 'View HRM file'; it said "Gdk-WARNING **: 13:55:20.714: XSetErrorHandler() called with a GDK error trap pushed. Don't do that."

So something went wrong in the installation, and now I need to figure out how to get the desktop icon back (clicking 'Show Applications' doesn't show SportsTracker) and I should be good.

Please PM me with a PayPal address; SportsTracker is worth it to me.

**Comment by ssaring** [comment]
Nice to hear that the SportsTracker application now runs successfully.

It seems that there are problem with the packaging system on your computer, it looks like the old and new versions are mixed up. On Ubuntu and Debian I'm always installing local packages with `dpkg -i ...` instead of `apt install ...`. The uninstall of the old version can be done with `sudo dpkg -r sportstracker` (I would suggest you to do this before). 
I'm not an Debian packaging expert, but maybe this works better for you. AFAIK `apt` is a wrapper / layer for `deb` which is not needed for local package processing.

**Comment by ssaring** [comment]
BTW: GitHub doesn't support PMs. You can contact me by using the GitHub user or project email address.

**Comment by QA-Manager** [comment]
Uninstalling and re-installing (with dpkg) worked; I have the desktop icon back. Thank you for all of your help.

**Comment by ssaring** [comment]
Great!
