### ISSUE TITLE
Are any of the sports watches really open?

### ISSUE THREAD

**Issue by QA-Manager** [ssaring/sportstracker#229]
Have any of the sports equipment manufacturers (particularly the watch manufacturers) published file formats? I know that the Garmin .FIT file is binary rather than something approachable like XML or JSON; I don't like binary files.

I want to support open formats with my purchases, but don't know which manufacturers are most or least open.

**Comment by ssaring** [comment]
I am very happy with Garmin devices because they are using the FIT file format and the ANT+ protocol. Both are well documented and SDKs are available for many programming languages. Here are some links:

* https://www.thisisant.com/developer/resources/downloads
* https://www.thisisant.com/developer/fit-sdk-release-notes

Yes, FIT is a binary format. But Garmin will have good reasons for that, especially for such smaller "embedded" devices with limited memore. That's fine for me, it's documented and the development by using the SDK is quite pleasent.

I had much worser experiences with devices from many other manufacturers, I don't want to name them here. Mostly no documentation war available, the binary formats were secret and reverse engineering was needed. This was very error prone and time consuming.
