### ISSUE TITLE
Request: set heart rate zones in preferences

### ISSUE THREAD

**Issue by janlul** [ssaring/sportstracker#235]
Hi,
I understand that only few devices support heart rate zones. They are valuable for me and it would be nice if I could pre-set them in the preferences. If they are overwritten in case they come from a device it would not matter.
When available they could be used in graphs which comes in handy to guesstimate training load and recovery time.
Sincere regards
Peter

**Comment by ssaring** [comment]
Currently there is no plan to support that. I already thought a few time about that, but it does not make sense in some cases. E.g. for Garmin users the HR zones are computed dynamically based on the current lactate treshold. If these would be stored fixed in the preferences, this would not match them and could be misleading.

And yes, the HR zone preferences could be optional. But even then, when you collect data for multiple years than the HR zones of today will not fit to the recorded exercises 5 years ago anymore.

Maybe there will be stronger demand in the future and / or someone can provide a reasonable and easy usable solution for that.

**Comment by ssaring** [comment]
Finally SportsTracker 7.8.1 (not released yet, but implementation available in master branch) supports displaying heartrate zones from the recorded FIT exercises, if this data is available. This is the case for most modern Garmin devices, also for some Suunto watches. 
So the majority of users can now see and use the heartrate zones without any additional effort and complexity. You can find further details in the discussion #242.
Therefore this issue / feature request can be closed.
