### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by asomers** [ssaring/sportstracker#237]
How can I install SportsTracker 7.7.0?  docs/README.txt says "download the ZIP archive with the application binaries".  But the only downloads I can find, from both Github and Sourceforge, don't contain the application binaries.  The only jar files are in the st-packager directory.  Alternatively, docs/README.txt also suggests that I can build the project with Maven.  But it doesn't tell me what arguments to use.  This is probably obvious to a Java developer, but I am not one.  Could you please supply it?

**Comment by ssaring** [comment]
You can find the native installable packages for Windows, Linux and macOS in the SourceForge projects site, linked in the GithHub project landing page. Because the installation is much easier with them, there is no binary-only ZIP archive with JAR files available anymore.

If you need them, the Maven build is quite simple: just install a recent JDK and Maven and execute "mvn clean package". You will find then the created JAR files then in sportstracker/target and sportstracker/target/lib directories.

You're right, in the README there's still the documentation for the ZIP JAR archive, I need to remove it.
