### ISSUE TITLE
incorrect view of preferences and diagrams

### ISSUE THREAD

**Issue by eanneser** [ssaring/sportstracker#246]
the Window/MsgBox for preferences and diagrams in SportsTracker 7.8.0 are not correct (see the Attachments).

![preferences](https://user-images.githubusercontent.com/89972448/131819440-58893afe-f9d7-4338-9cc7-0b9fb1f7c5e4.png)

![diagramm](https://user-images.githubusercontent.com/89972448/131818365-c07bbded-068c-4108-b1a0-d77ad133d5a6.png)

System: 
- Debian buster 10.10
- Installation: from sportstracker_7.8.0-1_amd64.deb
- Windowmanager: i3wm (4.16.1)

ST verion 7.7 worked fine on the same environment.

THX
E

**Comment by ssaring** [comment]
Interesting, this seems to be an specific issue. Tested on Ubuntu 20.04 with Gnome WindowManager and same installation package - no problems there.
Could you please test it with another WindowManager than i3wm on your Debian system, best with Gnome?

**Comment by eanneser** [comment]
If I install Gnome, everything works fine.
But - even with installed Gnome - if I use i3wm as WindowManager - the same fault.
It worked in ST version 7.7, so something must have been changed ...

**Comment by ssaring** [comment]
The difference is that ST 7.7.0 uses (or is packaged with) OpenJDK 11 and JavaFX 11 while ST 7.8.0 is using OpenJDK16 and JavaFX 16.
I'm quite sure that this WindowManager-dependent issue is not a SportsTracker implementation problem, this seems to be a bug in the OpenJDK 16 or JavaFX 16 Linux implementation. Version 17 of both will be released in a couple of days, with some luck this is a known issue and has been fixed there. If you are a bit familar with Java programming it should be quite easy to test that out. Otherwise you need to await the next SportsTracker release which will user the 17 versions.

I'll close this issue here, because it's not caused or fixable by SportsTracker. I would suggest you too look up whethere there are already bug reports on that for OpenJDK / JavaFX. So maybe you can find there a workaround for i3wm or you can file a new bug.
