### ISSUE TITLE
Swimming Activities Enhancements

### ISSUE THREAD

**Issue by zrlsid** [ssaring/sportstracker#255]
I suggest the following enhancements for the _SportsTracker_ application, which I've actually implemented in my own fork of this (great) project. However, it might come with the limitation to GARMIN / FIT applications.

**SportsTracker**

- On the _Add New Exercise_ view I allow the _sport type_ and the _sport subtype_ to be automatically synchronized with the FIT _session-sport_ and _session-subsport_ field.
- In case the FIT _session-sport_ does not exist in the selection, it will be added.

**ExerciseViewer**

- I've added following information on the _Optional_ tab under a label "Swim Training":

1. Pool Length
2. Aerobic Training Effect (with written explanation)
3. Anaerobic Training Effect (with written explanation)

- In the _Lap_ tab I've added following parameters:

1. Cadence
2. Strokes
3. Distance

- I've created a new tab called _Length_ which lists the information like in the _Lap_ per pool-length containing:

1. Length-nb
2. Time
3. Split-Time
4. Avg Speed
5. Avg Heart Rate
6. Strokes
7. Swim Style

- In the _Diagram_ tab one can also select now for the y-axis to display the following statistics:

1. Strokes (per length)
2. Cadence (per length)

Pls let me know if anything would be of interest for this main-project as well.

**Comment by ssaring** [comment]
**SportsTracker sport type / subtype matching**

* We're quite similar in laziness :) 
* I agree, would be good to extend the sport type list and sublist with the Garmin values for matching. Still unsure whether it makes sense to have it configurable for the user in the sport list setup dialog. Would be okayish to display the Garmin enum names in a a kind of readable way, but only in english. Proper names or even translations are not available. 
* The alternative would be to allow the mapping for 'pro-users' only in the sport_types.xml file via manual editing and assigning the Garmin IDs there. Normal users or users of other manufacturers would not be confused then.

**ExerciseViewer swim support**

* OK, got it. Diagram looks good!
* Unit tests would be really needed for the parser when adding swim data support.
* I agree, there are already multiple sections which are often not filled because of missing data. Nevertheless, those are quite common for multiple sport types anyway. E.g. power data can be for cycling, running, rowing etc. Or altitude data can be for almost all sport types if recoreded. Swim data is very specific, would prefer to have this panel only visible for swimming exercises.

**Comment by ssaring** [comment]
**SportsTracker sport type / subtype matching**

* Has been implemented in SportsTracker and already merged to the master branch. 
* The user needs to define the mapping between SportsTracker and FIT sport types and subtypes before, this can be done in the SportType Dialog.
* Whenever a matching mapping is found during importing FIT files, the appropriate sport type and subtype are preselected.

**ExerciseViewer swim support**

* Has not been implemented yet, as I don't have any test FIT exercise files and also not the swimming training and evaluation know-how.
* Would be great if the Swim support in ExerciseViewer could be contributed as a Pull Request, incl. unit tests.
* This contribution would be a new PR, therefore I close this issue here.
